<?php

return [
    'asm_agency_pekanbaru' => [
        'project_name' => 'Renovasi ASM Agency Pekanbaru',
        'location_province' => 'Riau',
        'location_city' => 'Kota Pekanbaru',
        'items' => [
            [
                'category' => 'Persiapan & Akhir',
                'item_name' => 'Mobilisasi dan Demobilisasi SDM, Alat dan Material',
                'specification' => 'Paket pekerjaan persiapan lapangan',
                'volume' => 1,
                'unit' => 'lot',
                'proposed_price' => 12000000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'Partisi Double Gypsum Ruang Pincab',
                'specification' => 'Jayaboard 9mm + Rangka Hollow 4x4 + Rockwool',
                'volume' => 6,
                'unit' => 'm2',
                'proposed_price' => 450000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'Partisi Double Gypsum Ruang Dealing',
                'specification' => 'Jayaboard 9mm + Rangka Hollow 4x4 + Rockwool',
                'volume' => 12,
                'unit' => 'm2',
                'proposed_price' => 450000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'Partisi Kaca Ruang Pincab',
                'specification' => 'Asahimas Clear Non Tempered 8mm',
                'volume' => 6,
                'unit' => 'm2',
                'proposed_price' => 650000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'Partisi Kaca Atas Pintu Ruang Pincab',
                'specification' => 'Asahimas Clear Non Tempered 8mm',
                'volume' => 1,
                'unit' => 'm2',
                'proposed_price' => 650000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'Partisi Kaca Atas Pintu Ruang Dealing',
                'specification' => 'Asahimas Clear Non Tempered 8mm',
                'volume' => 1,
                'unit' => 'm2',
                'proposed_price' => 650000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'Kusen Aluminium Partisi Kaca Ruang Pincab',
                'specification' => 'Alexindo 3 inch Powder Coating',
                'volume' => 10,
                'unit' => 'm1',
                'proposed_price' => 195000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'Kusen Aluminium Partisi Kaca Ruang Dealing',
                'specification' => 'Alexindo 3 inch Powder Coating',
                'volume' => 14.5,
                'unit' => 'm1',
                'proposed_price' => 195000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'Pintu Kaca Ruang Pincab',
                'specification' => 'Asahimas Clear Non Tempered 12mm',
                'volume' => 1,
                'unit' => 'unit',
                'proposed_price' => 5500000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'Pintu Kaca Ruang Dealing',
                'specification' => 'Asahimas Clear Non Tempered 12mm',
                'volume' => 1,
                'unit' => 'unit',
                'proposed_price' => 5500000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'Kusen Aluminium Pintu Kaca Ruang Pincab',
                'specification' => 'Alexindo 3 inch Powder Coating',
                'volume' => 4,
                'unit' => 'm1',
                'proposed_price' => 195000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'Kusen Aluminium Pintu Kaca Ruang Dealing',
                'specification' => 'Alexindo 3 inch Powder Coating',
                'volume' => 4,
                'unit' => 'm1',
                'proposed_price' => 195000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'Cat Finishing Semua Ruangan',
                'specification' => 'Jotun',
                'volume' => 158,
                'unit' => 'm2',
                'proposed_price' => 105000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'Sign Asuransi Sinar Mas Dinding Frontdesk',
                'specification' => 'Acrylic Laser Cutting',
                'volume' => 1,
                'unit' => 'ls',
                'proposed_price' => 2800000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'Sticker Sanblast Ruang Pincab',
                'specification' => 'Sanblast Motif Garis Standard ASM',
                'volume' => 3.6,
                'unit' => 'm2',
                'proposed_price' => 125000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'Sticker Sanblast Ruang Dealing',
                'specification' => 'Sanblast Motif Garis Standard ASM',
                'volume' => 3.6,
                'unit' => 'm2',
                'proposed_price' => 125000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'Sticker Asuransi Sinar Mas Pintu Entrance',
                'specification' => 'Oracal Laser Cutting Sticker',
                'volume' => 1,
                'unit' => 'ls',
                'proposed_price' => 725000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'Meja Frontdesk 120 x 60 cm',
                'specification' => 'Plywood 36mm Fin HPL Taco',
                'volume' => 1,
                'unit' => 'unit',
                'proposed_price' => 2200000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'Paket Lengkap Meja Afia (Meja Pincab, Meja Marketing)',
                'specification' => 'Paket custom furniture',
                'volume' => 1,
                'unit' => 'ls',
                'proposed_price' => 16164900,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'Stop Kontak Meja Staff',
                'specification' => 'Broco 4 Lubang',
                'volume' => 4,
                'unit' => 'unit',
                'proposed_price' => 185000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'Stop Kontak Dinding Ruang Staff',
                'specification' => 'Panasonic 1 Lubang',
                'volume' => 1,
                'unit' => 'unit',
                'proposed_price' => 140000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'Instalasi Kabel Stop Kontak Meja Staff',
                'specification' => 'NYM 3 x 2,5mm',
                'volume' => 4,
                'unit' => 'titik',
                'proposed_price' => 400000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'Lampu RM Eksisting Ruang Staff',
                'specification' => 'Armature & LED Bohlam TL 18x2 Watt',
                'volume' => 3,
                'unit' => 'unit',
                'proposed_price' => 175000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'Saklar Lampu RM Ruang Staff',
                'specification' => 'Panasonic 2 Gang',
                'volume' => 1,
                'unit' => 'unit',
                'proposed_price' => 250000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'Instalasi Kabel Saklar Lampu RM Ruang Staff',
                'specification' => 'NYM 3 x 1,5mm',
                'volume' => 1,
                'unit' => 'titik',
                'proposed_price' => 350000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'Pekerjaan Bongkar Pasang Indoor Outdoor AC 1,5 PK Ruang Staff',
                'specification' => 'Panasonic Inverter',
                'volume' => 1,
                'unit' => 'unit',
                'proposed_price' => 1870000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'Instalasi Pipa Refrigerant AC 1,5 PK',
                'specification' => 'R32 + Armaflex',
                'volume' => 30,
                'unit' => 'm1',
                'proposed_price' => 175000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'Instalasi Pipa Drain AC 1,5 PK',
                'specification' => '2 inch Rucika AW + Bobok Dinding dan Finishing Kembali',
                'volume' => 16,
                'unit' => 'm1',
                'proposed_price' => 295000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'AC 3/4 PK Ruang Pincab',
                'specification' => 'Panasonic Inverter',
                'volume' => 1,
                'unit' => 'unit',
                'proposed_price' => 7200000,
            ],
            [
                'category' => 'Pekerjaan Utama',
                'item_name' => 'AC 1/2 PK Ruang Frontdesk & Dealing',
                'specification' => 'Panasonic Inverter',
                'volume' => 2,
                'unit' => 'unit',
                'proposed_price' => 6850000,
            ],
        ],
    ],
];
